version: 2.1

workflows:
  version: 2
  Deploying Tic Tac:
     jobs: 
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.17.3
    steps:
      - checkout
      - run:
         name: installing Dependencies
         command: npm install
      

